import { ReactComponent as editIcon } from "../assets/icons/edit-2.svg";
import { ReactComponent as deleteIcon } from "../assets/icons/delete.svg";
import { ReactComponent as slashIcon } from "../assets/icons/slash.svg";
import { ReactComponent as checkIcon } from "../assets/icons/check-circle.svg";

export const customersInfo = [
  {
    id: 1,
    name: "Dina Glenn",
    phone: "(+99 893) 461-41-88",
    ordersCount: 3,
    status: "Aktiv",
    edit: editIcon,
    delete: deleteIcon,
    slash: slashIcon,
  },
  {
    id: 2,
    name: "Nicolina Lindholm",
    phone: "(+99 893) 461-41-88",
    ordersCount: 2,
    status: "Block",
    edit: editIcon,
    delete: deleteIcon,
    check: checkIcon,
  },
  {
    id: 3,
    name: "Ekaterina Tankova",
    phone: "(+99 893) 461-41-88",
    ordersCount: 1,
    status: "Aktiv",
    edit: editIcon,
    delete: deleteIcon,
    slash: slashIcon,
  },
  {
    id: 4,
    name: "Tum Tantasatityanon",
    phone: "(+99 893) 461-41-88",
    ordersCount: 1,
    status: "Block",
    edit: editIcon,
    delete: deleteIcon,
    check: checkIcon,
  },
  {
    id: 5,
    name: "Débora Barbosa",
    phone: "(+99 893) 461-41-88",
    ordersCount: 1,
    status: "Block",
    edit: editIcon,
    delete: deleteIcon,
    check: checkIcon,
  },
  {
    id: 6,
    name: "Sibabalwe Rubusana",
    phone: "(+99 893) 461-41-88",
    ordersCount: 6,
    status: "Aktiv",
    edit: editIcon,
    delete: deleteIcon,
    slash: slashIcon,
  },
  {
    id: 7,
    name: "Francisco Maia",
    phone: "(+99 893) 461-41-88",
    ordersCount: 1,
    status: "Aktiv",
    edit: editIcon,
    delete: deleteIcon,
    slash: slashIcon,
  },
  {
    id: 8,
    name: "Wilhelm Dowall",
    phone: "(+99 893) 461-41-88",
    ordersCount: 2,
    status: "Aktiv",
    edit: editIcon,
    delete: deleteIcon,
    slash: slashIcon,
  },
  {
    id: 9,
    name: "Wilhelm Dowall",
    phone: "(+99 893) 461-41-88",
    ordersCount: 8,
    status: "Aktiv",
    edit: editIcon,
    delete: deleteIcon,
    slash: slashIcon,
  },
  {
    id: 1,
    name: "Yvonne Thompson",
    phone: "(+99 893) 461-41-88",
    ordersCount: 8,
    status: "Aktiv",
    edit: editIcon,
    delete: deleteIcon,
    slash: slashIcon,
  },
];
